on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt 
    - run: pyinstaller -F mlsetup.py
    - name: get datat
      run: ls -ltrh 
#    - uses: actions/upload-artifact@v2
#      with:
#        path: dist/*
